
import type { Course, Contact, FaqItem, GeneralInfo } from '@/lib/types';

export const courses: Course[] = [
  // Arts / Humanities
  {
    id: 'ba-gen',
    title: 'B.A. (Bachelor of Arts)',
    department: 'Arts / Humanities',
    code: 'BA101',
    description: 'A foundational undergraduate degree offering a broad education in the humanities and social sciences.',
    eligibility: '10+2 or equivalent examination from a recognized board.',
    duration: '3 Years',
    credits: 120,
    feeStructure: {
      'Annual Fee': 50000,
      'Semester 1': 25000,
      'Semester 2': 25000,
      'Semester 3': 25000,
      'Semester 4': 25000,
      'Semester 5': 25000,
      'Semester 6': 25000,
    },
    placementInfo: 'Graduates can explore careers in civil services, journalism (The Times Group), social work, and public relations (Edelman). Average starting salary is around 3-5 LPA, with highest packages reaching up to 7 LPA.',
  },
  {
    id: 'bfa',
    title: 'BFA (Bachelor of Fine Arts)',
    department: 'Arts / Humanities',
    code: 'BFA101',
    description: 'A specialized degree for students aiming for a creative career in visual or performing arts.',
    eligibility: '10+2 or equivalent. Some universities may require a portfolio or entrance test.',
    duration: '4 Years',
    credits: 160,
    feeStructure: {
      'Annual Fee': 75000,
      'Semester 1': 37500,
      'Semester 2': 37500,
      'Semester 3': 37500,
      'Semester 4': 37500,
      'Semester 5': 37500,
      'Semester 6': 37500,
      'Semester 7': 37500,
      'Semester 8': 37500,
    },
    placementInfo: 'Opportunities in animation (DreamWorks), graphic design (Adobe), and art direction. Placements with creative agencies like Ogilvy. Highest packages can go up to 10 LPA.',
  },
  {
    id: 'bjmc',
    title: 'BJMC (Journalism & Mass Communication)',
    department: 'Arts / Humanities',
    code: 'BJMC101',
    description: 'A program designed to equip students with the skills for a career in media, journalism, and public relations.',
    eligibility: '10+2 with a minimum of 50% marks. Entrance exam may be required.',
    duration: '3 Years',
    credits: 130,
    feeStructure: {
      'Annual Fee': 90000,
      'Semester 1': 45000,
      'Semester 2': 45000,
      'Semester 3': 45000,
      'Semester 4': 45000,
      'Semester 5': 45000,
      'Semester 6': 45000,
    },
    placementInfo: 'Placements in leading news channels (India Today Group), newspapers (Hindustan Times), and digital media agencies. Highest packages have gone up to 8 LPA.',
  },
  {
    id: 'ba-llb',
    title: 'BA LLB (Integrated Law)',
    department: 'Arts / Humanities',
    code: 'LAW101',
    description: 'An integrated five-year program combining arts and law subjects, leading to a professional law degree.',
    eligibility: '10+2 or equivalent. Admission is typically through a national-level law entrance exam (e.g., CLAT).',
    duration: '5 Years',
    credits: 200,
    feeStructure: {
      'Annual Fee': 150000,
      'Semester 1': 75000,
      'Semester 2': 75000,
      'Semester 3': 75000,
      'Semester 4': 75000,
      'Semester 5': 75000,
      'Semester 6': 75000,
      'Semester 7': 75000,
      'Semester 8': 75000,
      'Semester 9': 75000,
      'Semester 10': 75000,
    },
    placementInfo: 'Excellent placements in corporate law firms like Amarchand Mangaldas and Khaitan & Co. Average package for top graduates is 10-15 LPA, with highest offers reaching 20 LPA.',
  },
  // Science
  {
    id: 'bsc-gen',
    title: 'B.Sc. (Bachelor of Science)',
    department: 'Science',
    code: 'BSC101',
    description: 'A fundamental science degree with options to specialize in various scientific disciplines.',
    eligibility: '10+2 with a science stream (Physics, Chemistry, Biology/Maths) from a recognized board.',
    duration: '3 Years',
    credits: 120,
    feeStructure: {
      'Annual Fee': 60000,
      'Semester 1': 30000,
      'Semester 2': 30000,
      'Semester 3': 30000,
      'Semester 4': 30000,
      'Semester 5': 30000,
      'Semester 6': 30000,
    },
    placementInfo: 'Career paths in research (Biocon), healthcare, and IT (TCS). Many students opt for higher studies for better prospects. Highest packages around 6 LPA.',
  },
  {
    id: 'btech-be',
    title: 'B.Tech / BE (Engineering)',
    department: 'Science',
    code: 'ENG101',
    description: 'A professional engineering degree with specializations like Computer Science, Mechanical, Civil, and Electrical.',
    eligibility: '10+2 with Physics, Chemistry, and Mathematics (PCM). Admission is based on entrance exams like JEE Main.',
    duration: '4 Years',
    credits: 180,
    feeStructure: {
      'Annual Fee': 180000,
      'Semester 1': 90000,
      'Semester 2': 90000,
      'Semester 3': 90000,
      'Semester 4': 90000,
      'Semester 5': 90000,
      'Semester 6': 90000,
      'Semester 7': 90000,
      'Semester 8': 90000,
    },
    placementInfo: 'Over 90% placement rate with top recruiters like Google, Microsoft, and Amazon. Average package for CSE is 12 LPA. Highest package offered was 45 LPA by Atlassian.',
  },
  {
    id: 'bca',
    title: 'BCA (Computer Applications)',
    department: 'Science',
    code: 'BCA101',
    description: 'A three-year undergraduate program focused on computer science and its applications.',
    eligibility: '10+2 with Mathematics as a subject. Some universities may admit students from other streams.',
    duration: '3 Years',
    credits: 140,
    feeStructure: {
      'Annual Fee': 85000,
      'Semester 1': 42500,
      'Semester 2': 42500,
      'Semester 3': 42500,
      'Semester 4': 42500,
      'Semester 5': 42500,
      'Semester 6': 42500,
    },
    placementInfo: 'Strong placements in the IT sector with companies like TCS, Infosys, and Wipro. Roles include software developer and system analyst. Highest package around 9 LPA.',
  },
  {
    id: 'mbbs',
    title: 'MBBS (Medicine)',
    department: 'Science',
    code: 'MED101',
    description: 'An undergraduate medical degree required to become a doctor of medicine.',
    eligibility: '10+2 with Physics, Chemistry, Biology (PCB). Admission is through the NEET UG entrance exam.',
    duration: '5.5 Years (including internship)',
    credits: 250,
    feeStructure: {
      'Annual Fee': 500000,
      'Year 1': 500000,
      'Year 2': 500000,
      'Year 3': 500000,
      'Year 4': 500000,
      'Year 5': 250000,
    },
    placementInfo: '100% internship placement in affiliated hospitals. Graduates join top hospital chains like Apollo and Fortis, with starting salaries ranging from 12-18 LPA.',
  },
  {
    id: 'bds',
    title: 'BDS (Dentistry)',
    department: 'Science',
    code: 'DEN101',
    description: 'An undergraduate degree for students who want to pursue a career in dentistry.',
    eligibility: '10+2 with PCB. Admission is through the NEET UG entrance exam.',
    duration: '5 Years (including internship)',
    credits: 220,
    feeStructure: {
      'Annual Fee': 350000,
      'Year 1': 350000,
      'Year 2': 350000,
      'Year 3': 350000,
      'Year 4': 350000,
    },
    placementInfo: 'Graduates can work in private or government dental clinics like Clove Dental. Many open their own private practice, with potential earnings exceeding 10 LPA.',
  },
  {
    id: 'bpharm',
    title: 'B.Pharm (Pharmacy)',
    department: 'Science',
    code: 'PHM101',
    description: 'A four-year program that prepares students for roles in the pharmaceutical industry, drug research, and medical dispensing.',
    eligibility: '10+2 with PCB or PCM stream. Pharmacy entrance exams may be required.',
    duration: '4 Years',
    credits: 170,
    feeStructure: {
      'Annual Fee': 120000,
      'Semester 1': 60000,
      'Semester 2': 60000,
      'Semester 3': 60000,
      'Semester 4': 60000,
      'Semester 5': 60000,
      'Semester 6': 60000,
      'Semester 7': 60000,
      'Semester 8': 60000,
    },
    placementInfo: 'Placements in major pharmaceutical companies like Cipla and Sun Pharma. Roles in R&D and quality control. Highest packages can go up to 10 LPA.',
  },
  // Commerce / Management
  {
    id: 'bcom',
    title: 'B.Com (Bachelor of Commerce)',
    department: 'Commerce / Management',
    code: 'BCOM101',
    description: 'An undergraduate degree in commerce and related subjects, providing a strong foundation in business and finance.',
    eligibility: '10+2 with commerce stream or equivalent.',
    duration: '3 Years',
    credits: 120,
    feeStructure: {
      'Annual Fee': 55000,
      'Semester 1': 27500,
      'Semester 2': 27500,
      'Semester 3': 27500,
      'Semester 4': 27500,
      'Semester 5': 27500,
      'Semester 6': 27500,
    },
    placementInfo: 'Opportunities in banking, accounting (KPMG), and finance sectors. Placements with firms like Deloitte and EY. Highest packages up to 10 LPA for specialized roles.',
  },
  {
    id: 'bba',
    title: 'BBA (Business Administration)',
    department: 'Commerce / Management',
    code: 'BBA101',
    description: 'A bachelor’s degree that provides a broad understanding of business principles and management functions.',
    eligibility: '10+2 from any stream. Some universities conduct entrance tests.',
    duration: '3 Years',
    credits: 130,
    feeStructure: {
      'Annual Fee': 95000,
      'Semester 1': 47500,
      'Semester 2': 47500,
      'Semester 3': 47500,
      'Semester 4': 47500,
      'Semester 5': 47500,
      'Semester 6': 47500,
    },
    placementInfo: 'Placements in marketing (HUL), sales (Amazon), and HR roles. Top recruiters include HDFC Bank and Amazon. Highest package offered was 12 LPA.',
  },
  // Professional Courses
  {
    id: 'bhm',
    title: 'BHM (Hotel Management)',
    department: 'General / Professional',
    code: 'BHM101',
    description: 'A degree program that prepares students for a career in the hospitality industry, including hotels, resorts, and restaurants.',
    eligibility: '10+2 from any stream. Admission often based on entrance exams like NCHMCT JEE.',
    duration: '4 Years',
    credits: 160,
    feeStructure: {
      'Annual Fee': 130000,
      'Semester 1': 65000,
      'Semester 2': 65000,
      'Semester 3': 65000,
      'Semester 4': 65000,
      'Semester 5': 65000,
      'Semester 6': 65000,
      'Semester 7': 65000,
      'Semester 8': 65000,
    },
    placementInfo: 'Placements in leading hotel chains like Taj, Oberoi, and Marriott with management trainee programs. Highest packages can reach 8 LPA.',
  },
  {
    id: 'bdes',
    title: 'B.Des (Fashion Designing)',
    department: 'General / Professional',
    code: 'BDES101',
    description: 'A creative degree focusing on the art and business of fashion design, from concept to production.',
    eligibility: '10+2 from any stream. A portfolio and entrance exam (like NID/NIFT) are typically required.',
    duration: '4 Years',
    credits: 160,
    feeStructure: {
      'Annual Fee': 160000,
      'Semester 1': 80000,
      'Semester 2': 80000,
      'Semester 3': 80000,
      'Semester 4': 80000,
      'Semester 5': 80000,
      'Semester 6': 80000,
      'Semester 7': 80000,
      'Semester 8': 80000,
    },
    placementInfo: 'Graduates work with top fashion brands like Zara and H&M, and designers like Manish Malhotra. Highest packages for merchandisers can reach 15 LPA.',
  },
];


export const contacts: Contact[] = [
  {
    id: '1',
    name: 'Dr. Priya Sharma',
    title: 'Head of Admissions',
    department: 'Admissions Office',
    email: 'p.sharma@university.ac.in',
    phone: '+91 98765 43210',
    avatarId: 'contact-1',
  },
  {
    id: '2',
    name: 'Mr. Rajesh Kumar',
    title: 'Financial Aid Advisor',
    department: 'Financial Aid Office',
    email: 'r.kumar@university.ac.in',
    phone: '+91 98765 43211',
    avatarId: 'contact-2',
  },
  {
    id: '3',
    name: 'Dr. Anjali Singh',
    title: 'Dean of Engineering',
    department: 'Engineering Department',
    email: 'a.singh@university.ac.in',
    phone: '+91 98765 43212',
    avatarId: 'contact-3',
  },
  {
    id: '4',
    name: 'Prof. Vikram Mehta',
    title: 'Head of Management Studies',
    department: 'Management Department',
    email: 'v.mehta@university.ac.in',
    phone: '+91 98765 43213',
    avatarId: 'contact-4',
  },
];

export const faqs: FaqItem[] = [
  // General Admission Queries
  {
    id: 'faq1',
    question: 'What are the eligibility criteria for admission?',
    answer: 'Eligibility criteria vary by course. Generally, applicants must have passed the Class 12 (or equivalent) examination. Specific stream requirements (like PCM for Engineering or PCB for Medical) and minimum percentage criteria apply for most programs. Please check the specific course page for detailed information.',
  },
  {
    id: 'faq2',
    question: 'What is the admission process or procedure?',
    answer: 'The admission process includes: 1. Registering on the official portal. 2. Filling out the application form. 3. Uploading required documents. 4. Paying the application fee. 5. Appearing for entrance exams (if applicable). 6. Participating in counseling and seat allotment.',
  },
  {
    id: 'faq3',
    question: 'When does the admission process start and end?',
    answer: 'The admission process for the main session typically starts in March and ends by July. The Fall session deadline is April 30th, and the Spring session is November 30th. Please monitor the official university website for exact dates.',
  },
  {
    id: 'faq4',
    question: 'Is the admission form available online or offline?',
    answer: 'Admission forms are available exclusively online through our official admission portal. We do not provide offline application forms.',
  },
  {
    id: 'faq5',
    question: 'What are the application deadlines?',
    answer: 'The application deadline for the main session is typically in April. For exact dates regarding entrance exams like JEE and NEET, or university-specific deadlines, please check the respective official websites.',
  },
  {
    id: 'faq6',
    question: 'What documents are required for admission?',
    answer: 'You will need to submit your Class 10th and 12th mark sheets, a valid government-issued photo ID (like Aadhar Card), passport-sized photographs, and a category certificate (if applicable).',
  },
  {
    id: 'faq7',
    question: 'Is there an entrance exam? If so, what is the syllabus and pattern?',
    answer: 'Yes, admission to professional courses like Engineering (B.Tech), Medicine (MBBS), and Law (BA LLB) is based on national-level entrance exams (JEE Main, NEET UG, CLAT). The syllabus and pattern are determined by the conducting authorities of these exams.',
  },
  {
    id: 'faq8',
    question: 'What are the important dates (admission test, interview, counseling)?',
    answer: 'All important dates, including test schedules, interview calls, and counseling dates, are published on the university\'s official admissions page. Please check it regularly for updates.',
  },
  {
    id: 'faq9',
    question: 'How do I check the status of my application?',
    answer: 'You can check your application status by logging into the admission portal with the credentials you received during registration.',
  },
  {
    id: 'faq10',
    question: 'What is the mode of instruction (online, offline, hybrid)?',
    answer: 'All our programs are conducted in a full-time, offline (in-person) mode at the campus. We do not currently offer hybrid or fully online degree programs.',
  },
  // Fee & Payment Queries
  {
    id: 'faq11',
    question: 'What is the fee structure for the program?',
    answer: 'The fee structure varies for each program. Please select a specific course on our "Courses" page to view detailed fee information, including annual and semester-wise breakdowns.',
  },
  {
    id: 'faq12',
    question: 'Is there any scholarship or financial aid available?',
    answer: 'Yes, we offer merit-based and need-based scholarships. Students can also apply for various government scholarships through the National Scholarship Portal. Please visit our Financial Aid office for more details.',
  },
  {
    id: 'faq13',
    question: 'Are there installment options for fee payment?',
    answer: 'Yes, fees can be paid on a semester-wise or annual basis. We do not offer further monthly installment plans, but we have tie-ups with banks for education loans.',
  },
  {
    id: 'faq14',
    question: 'Is the application fee refundable?',
    answer: 'The application fee is non-refundable under any circumstances.',
  },
  {
    id: 'faq15',
    question: 'What modes of payment are accepted?',
    answer: 'We accept online payments through net banking, credit cards, debit cards, and UPI. We do not accept cash payments for tuition or application fees.',
  },
  // Quota & Reservation Queries
  {
    id: 'faq16',
    question: 'Are there any reserved seats (SC/ST/OBC/EWS/PWD)?',
    answer: 'Yes, we adhere to the reservation policies mandated by the Government of India for all our programs. Seats are reserved for SC, ST, OBC, EWS, and PWD categories.',
  },
  {
    id: 'faq17',
    question: 'Is there a management or donation quota?',
    answer: 'No, admissions are strictly based on merit and entrance exam scores. We do not have a management quota or accept donations for admission.',
  },
  // Accommodation & Campus Facilities
  {
    id: 'faq18',
    question: 'Is hostel accommodation available?',
    answer: 'Yes, we offer separate, fully-furnished hostel facilities for boys and girls with options for AC and non-AC rooms.',
  },
  {
    id: 'faq19',
    question: 'What are the hostel fees and facilities?',
    answer: 'Hostel fees are ₹60,000 per year, which includes lodging and mess facilities. Hostels are equipped with Wi-Fi, common rooms, and 24/7 security.',
  },
  {
    id: 'faq31',
    question: 'What are the bus fees and routes?',
    answer: 'The university provides bus services from various nearby locations. The annual fee depends on the route. For example, the fee for Gokul is ₹20,000, for Govardhan is ₹22,000, and for Barsana is ₹25,000. Please contact the transport department for a complete list of routes and their respective fees.',
  },
  {
    id: 'faq20',
    question: 'What are the campus amenities (library, labs, Wi-Fi, etc.)?',
    answer: 'Our campus is equipped with state-of-the-art facilities, including a 24/7 central library, modern laboratories for all departments, high-speed Wi-Fi across the campus, a sports complex, and multiple canteens.',
  },
  // International Student Queries
  {
    id: 'faq21',
    question: 'Is admission open to international students?',
    answer: 'Yes, we welcome applications from international students. There is a separate admission process and a dedicated international admissions office to assist you.',
  },
  {
    id: 'faq22',
    question: 'What are the visa requirements?',
    answer: 'International students must obtain a valid student visa from the Indian embassy in their country. The university will provide the necessary documentation to support your visa application upon successful admission.',
  },
  // Post-Admission Queries
  {
    id: 'faq23',
    question: 'When will the classes start?',
    answer: 'The academic session for newly admitted students typically begins in the first week of August. You will receive a detailed academic calendar upon admission.',
  },
  {
    id: 'faq24',
    question: 'How do I get my ID card or enrollment number?',
    answer: 'ID cards and enrollment numbers are issued within the first week of the commencement of classes. You will be notified of the schedule for the same.',
  },
  {
    id: 'faq25',
    question: 'What is the process for withdrawal or refund?',
    answer: 'The withdrawal and refund policy is governed by UGC guidelines. Please refer to the admission brochure or contact the admissions office for detailed information on the procedure and refund eligibility.',
  },
  // Placement Queries
  {
    id: 'faq26',
    question: 'What are the placement opportunities for B.Tech students?',
    answer: 'Our B.Tech program has an excellent placement record, with over 90% of students placed. Top recruiters include Google, Microsoft, Amazon, and Atlassian. The average salary for Computer Science is 12 LPA, with the highest package being 45 LPA. Other branches like Mechanical and Civil average 6-8 LPA.',
  },
  {
    id: 'faq27',
    question: 'What kind of jobs can I get after a BBA?',
    answer: 'BBA graduates get roles in marketing, sales, and HR. Top recruiters include HUL, Amazon, and HDFC Bank, with an average salary of 5-8 LPA and a highest package of 12 LPA.',
  },
  {
    id: 'faq28',
    question: 'Are there placements for B.Sc. graduates?',
    answer: 'While many B.Sc. graduates pursue higher studies, there are placement opportunities in IT (TCS), research labs (Biocon), and pharmaceutical companies. The highest package is around 6 LPA.',
  },
  {
    id: 'faq29',
    question: 'Do you have a dedicated placement cell?',
    answer: 'Yes, our university has a dedicated Training and Placement Cell that works year-round to connect students with top employers. They organize workshops, mock interviews, and recruitment drives to prepare students for their careers. They are the primary point of contact for all placement-related activities.',
  },
  {
    id: 'faq30',
    question: 'What is the highest salary package offered?',
    answer: 'The highest salary package varies by course. For B.Tech in Computer Science, it was 45 LPA from Atlassian. For BBA, it was 12 LPA. For law, it has reached 20 LPA from top corporate firms. We encourage you to ask about specific courses for detailed placement statistics.',
  },
];

export const generalInfo: GeneralInfo = {
  applicationDeadlines: {
    fall: 'April 30th',
    spring: 'November 30th',
  },
  requiredDocuments: [
    'Class 10th Marksheet',
    'Class 12th Marksheet',
    'Aadhar Card',
    'Passport-sized photographs',
    'Category Certificate (if applicable)',
  ],
  applicationSteps: [
    'Register online on the official portal.',
    'Fill out the application form with correct details.',
    'Upload scanned copies of required documents.',
    'Pay the application fee online.',
    'Download and print the confirmation page.',
  ],
  fees: 'Tuition fees vary by course. Please ask about a specific course for detailed fee information. Hostel fees are ₹60,000 per year. Bus fees vary by route. These fees are subject to revision.',
  busFees: {
    'Gokul': 20000,
    'Barsana': 25000,
    'Govardhan': 22000,
    'Nandgaon': 24000,
    'Radhakund': 21000,
    'Baldeo': 23000,
    'Mahavan': 20500,
  },
  eligibility: 'Eligibility criteria vary by course. Generally, applicants must have passed the Class 12 (or equivalent) examination. Specific stream requirements (like PCM for Engineering or PCB for Medical) and minimum percentage criteria apply for most programs. Admission may also be based on national-level entrance exams.',
  facilities: 'Our campus boasts state-of-the-art facilities, including modern laboratories, a 24/7 library, a sports complex with cricket and football grounds, multiple canteens, and student common rooms. High-speed Wi-Fi is available across the entire campus.',
  entranceExams: 'Admission to professional courses like Engineering (B.Tech), Medicine (MBBS), and Law (BA LLB) is based on national-level entrance exams (JEE Main, NEET UG, CLAT respectively).',
  applicationStatus: 'You can check your application status by logging into the admission portal with the credentials provided during registration.',
  internationalAdmissions: 'Yes, we welcome international students. Please contact our international admissions office for details on the application process, visa requirements, and fees.',
  placements: 'Our university has a dedicated Training and Placement Cell with a strong track record. We have over 90% placement rate for professional courses like B.Tech, with top recruiters like Google, Microsoft, and Amazon. Average packages vary by branch. For specific details, please ask about placement for a particular course.',
};
